# Generated by Django 4.1.7 on 2023-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='WTF Contest')),
                ('category', models.TextField(default='Maths')),
                ('tags', models.JSONField(default=list)),
                ('intro', models.TextField(default='Some nice team.')),
                ('members', models.ManyToManyField(to='main.user_data')),
            ],
        ),
    ]
