# Generated by Django 4.1.7 on 2023-10-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_author_id_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='intro',
        ),
        migrations.AddField(
            model_name='team',
            name='职位',
            field=models.JSONField(default=dict),
        ),
    ]
