# Generated by Django 4.1.7 on 2023-10-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_team_intro_team_职位'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='职位',
            new_name='positions',
        ),
    ]
